INSERT INTO product (name, price) VALUES ('Pão francês', 0.50);
INSERT INTO product (name, price) VALUES ('Pão de forma', 3.00);
INSERT INTO product (name, price) VALUES ('Baguete', 2.50);
INSERT INTO product (name, price) VALUES ('Croissant', 3.00);
INSERT INTO product (name, price) VALUES ('Rosquinha', 1.00);
INSERT INTO product (name, price) VALUES ('Torrada', 2.00);
INSERT INTO product (name, price) VALUES ('Bolo de cenoura', 6.00);
INSERT INTO product (name, price) VALUES ('Bolo de fubá', 5.00);
INSERT INTO product (name, price) VALUES ('Bolo de laranja', 5.50);
INSERT INTO product (name, price) VALUES ('Bolo de milho', 5.00);
INSERT INTO product (name, price) VALUES ('Bolo de coco', 7.00);
INSERT INTO product (name, price) VALUES ('Bolo de abacaxi', 8.00);
INSERT INTO product (name, price) VALUES ('Coxinha', 2.50);
INSERT INTO product (name, price) VALUES ('Empada', 3.00);
INSERT INTO product (name, price) VALUES ('Esfirra', 2.00);
INSERT INTO product (name, price) VALUES ('Pastel de carne', 2.50);
INSERT INTO product (name, price) VALUES ('Pastel de queijo', 2.50);
INSERT INTO product (name, price) VALUES ('Pão de queijo', 1.50);
INSERT INTO product (name, price) VALUES ('Quiche', 4.00);
INSERT INTO product (name, price) VALUES ('Torta de frango', 6.00);
INSERT INTO product (name, price) VALUES ('Torta de palmito', 6.50);
INSERT INTO product (name, price) VALUES ('Torta de limão', 5.50);
INSERT INTO product (name, price) VALUES ('Torta de morango', 6.00);
INSERT INTO product (name, price) VALUES ('Refrigerante', 4.00);
INSERT INTO product (name, price) VALUES ('Água mineral', 2.00);
INSERT INTO product (name, price) VALUES ('Café', 2.00);
INSERT INTO product (name, price) VALUES ('Cappuccino', 4.50);
INSERT INTO product (name, price) VALUES ('Chá gelado', 3.00);
INSERT INTO product (name, price) VALUES ('Iogurte', 3.00);
INSERT INTO product (name, price) VALUES ('Leite', 3.50);
INSERT INTO product (name, price) VALUES ('Achocolatado', 2.50);
INSERT INTO product (name, price) VALUES ('Biscoito', 2.00);
INSERT INTO product (name, price) VALUES ('Bolacha recheada', 2.50);
INSERT INTO product (name, price) VALUES ('Amendoim', 3.00);
INSERT INTO product (name, price) VALUES ('Batata frita', 2.50);
INSERT INTO product (name, price) VALUES ('Chips de batata', 3.00);
INSERT INTO product (name, price) VALUES ('Pipoca', 2.00);
INSERT INTO product (name, price) VALUES ('Barra de cereal', 2.00);
INSERT INTO product (name, price) VALUES ('Granola', 3.00);
INSERT INTO product (name, price) VALUES ('Mel', 5.00);
INSERT INTO product (name, price) VALUES ('Geléia', 4.00);
INSERT INTO product (name, price) VALUES ('Queijo mussarela', 15.00);
INSERT INTO product (name, price) VALUES ('Queijo prato', 14.00);
INSERT INTO product (name, price) VALUES ('Presunto', 10.00);
INSERT INTO product (name, price) VALUES ('Salame', 12.00);
INSERT INTO product (name, price) VALUES ('Mortadela', 8.00);
INSERT INTO product (name, price) VALUES ('Manteiga', 5.00);
INSERT INTO product (name, price) VALUES ('Requeijão', 4.50);
